
export interface User {
  id: string;
  name: string;
  email: string;
  quota: {
    used: number;
    total: number;
    resetDate: string;
  };
  tier: 'free' | 'plus' | 'pro';
}

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
}

export type ViewMode = 'list' | 'canvas';

export interface Project {
  id: string;
  title: string;
  description: string;
  lastUpdate: number;
  status: 'draft' | 'rendering' | 'completed';
  type: 'T2V' | 'I2V';
  thumbnailUrl?: string;
  selectedCharacterIds?: string[];
  characterInvariants?: any[];
  currentFocusNodeId?: string; // The currently active "Head" of the timeline
  invariants: {
    visualStyle?: string;
    negativePrompt?: string;
    aspectRatio?: string;
  };
  deletedAt?: number; // Timestamp for soft delete
}

export type Session = Project;

export type CoherenceStatus = 'VALID' | 'BROKEN' | 'HEALED';
export type NodeStatus = 'pending' | 'generating' | 'completed' | 'failed';
export type RenderStage = 'QUEUED' | 'ENRICHING' | 'LOADING' | 'SAMPLING' | 'ENCODING' | 'UPLOADING' | 'DONE';

export interface RenderTask {
  id: string;
  nodeId: string;
  stage: RenderStage;
  pct: number;
}

export interface StoryNode {
  id: string;
  projectId: string;
  parentId: string | null;
  branchId: string;
  index: number;
  prompt: string;
  technicalPrompt?: string; // The actual T5 prompt generated by Director
  userIntent?: string; // What the user originally typed
  status: NodeStatus;
  renderStage?: RenderStage;
  progress?: number;
  coherenceStatus: CoherenceStatus;
  createdAt: number;
  assets: {
    videoOpfsPath?: string;
    anchorPngOpfsPath?: string;
    videoUrl?: string;
  };
  // For UI visualization
  previewOptions?: DirectorOption[]; // The options that LED to this node (if selected via option)
}

export interface DirectorOption {
  id: string;
  category: 'NARRATIVE' | 'VISUAL' | 'TECHNICAL';
  label: string;
  description: string;
  prompt_addon: string;
}

export interface Attachment {
  type: 'image';
  url: string;
  base64?: string;
}

export interface PromptDraft {
  anchor: string;
  delta: string;
  negative: string;
  duration?: string;
  aspectRatio?: string;
}

export interface Message {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  options?: DirectorOption[];
  promptDraft?: PromptDraft; // If present, UI renders the "Production Manifest" editor
  nodeId?: string; // Link message to a specific node creation event
  attachments?: Attachment[];
  suggestions?: string[];
  isSystemEvent?: boolean; // For "Rendering started..." messages
  reasoning?: string; // For "Thinking" models (Chain of Thought)
}

export interface CharacterProfile {
  name: string;
  identity: {
    gender: string;
    age: string;
    species: string; 
    archetype: string;
  };
  appearance: {
    features: string;
    hair: string; 
    hairstyle: string; 
    eyes: string;
    build: string;
  };
  wardrobe: {
    description: string;
    accessories: string;
  };
  vibe: {
    mood: string;
    style: string;
  };
  special: {
    distinctive_features: string;
    behavior: string;
    likes: string;
  };
}

export interface Character {
  id: string;
  name: string;
  portrait: string; 
  rawPortrait?: string; 
  referenceImage?: string; 
  tags: string[];
  lastUsed: number;
}

export enum NavigationTab {
  CHAT = 'chat',
  CAST = 'cast',
  PROFILE = 'profile'
}
